# Headless Service
apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
  labels:
    app: nginx
    purpose: stateful-demo
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
    purpose: stateful-demo

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
      purpose: stateful-demo

  serviceName: nginx-headless

  replicas: 3

  template:
    metadata:
      labels:
        app: nginx
        purpose: stateful-demo

    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: web
       