apiVersion: v1
kind: Pod

metadata:
  name: nginx-emptydir
  namespace: roboshop

spec:
  containers:
    - name: nginx
      image: nginx

      volumeMounts:
        - name: temp-storage
          mountPath: /data

  volumes:
    - name: temp-storage
      emptyDir: {}